name: Continuous Integration
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
       
    steps:
      - uses: actions/checkout@v2
   
      - name: set up all python versions
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
       
      - name: Install python dependencies
        run: pip install -r requirements.txt
       
      - name: Run Tests
        run: python -m unittest discover test_units